using System.IO.Compression;
using System.Text;
using Braavo.Core.Interfaces;
using Braavo.Core.UseCases.Prd;
using MediatR;

namespace Braavo.Core.UseCases.Export;

public class ExportBundleHandler : IRequestHandler<ExportBundleCommand, ExportResult>
{
    private readonly IDocumentRepository _documents;

    public ExportBundleHandler(IDocumentRepository documents) => _documents = documents;

    public async Task<ExportResult> Handle(ExportBundleCommand request, CancellationToken ct)
    {
        var document = await _documents.GetByIdAsync(request.DocumentId, ct);
        if (document is null)
            return new ExportResult([], "", false, "Document not found");

        if (document.CreatedBy.Value != request.UserId)
        {
            return new ExportResult(Array.Empty<byte>(), "", false, "Forbidden");
        }

        var prd = PrdParser.Parse(document.Content);
        var sanitizedTitle = SanitizeFileName(prd.Title);

        using var memoryStream = new MemoryStream();
        using (var archive = new ZipArchive(memoryStream, ZipArchiveMode.Create, true))
        {
            AddEntry(archive, "PRD.md", document.Content);
            AddEntry(archive, "user-stories.md", ExportUserStories(prd));
            AddEntry(archive, "features.md", ExportFeatures(prd));
            AddEntry(archive, "metrics.md", ExportMetrics(prd));
            AddEntry(archive, "README.md", GenerateReadme(prd));
        }

        // TODO: When IncludeDiagrams is true, generate and add diagram files to diagrams/ folder
        if (request.IncludeDiagrams)
        {
            // Placeholder for diagram export - requires diagram generation service
        }

        memoryStream.Position = 0;
        var fileName = $"{sanitizedTitle}-export.zip";

        return new ExportResult(memoryStream.ToArray(), fileName, true);
    }

    private static void AddEntry(ZipArchive archive, string name, string content)
    {
        var entry = archive.CreateEntry(name, CompressionLevel.Optimal);
        using var writer = new StreamWriter(entry.Open(), Encoding.UTF8);
        writer.Write(content);
    }

    private static string SanitizeFileName(string name)
    {
        var invalid = Path.GetInvalidFileNameChars();
        return string.Concat(name.Where(c => !invalid.Contains(c))).Replace(" ", "-").ToLowerInvariant();
    }

    private static string ExportUserStories(Models.PrdContent prd)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# User Stories\n");
        foreach (var story in prd.UserStories)
        {
            sb.AppendLine($"- **As a** {story.AsA}, **I want** {story.IWant} **so that** {story.SoThat}");
        }
        return sb.ToString();
    }

    private static string ExportFeatures(Models.PrdContent prd)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Features\n");
        foreach (var feature in prd.Features)
        {
            sb.AppendLine($"## {feature.Name}\n{feature.Description}\n");
        }
        return sb.ToString();
    }

    private static string ExportMetrics(Models.PrdContent prd)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Success Metrics\n");
        foreach (var metric in prd.SuccessMetrics)
        {
            sb.AppendLine($"- {metric}");
        }
        return sb.ToString();
    }

    private static string GenerateReadme(Models.PrdContent prd) => $"""
        # {prd.Title}

        This export bundle contains:

        - `PRD.md` - Full Product Requirements Document
        - `user-stories.md` - Extracted user stories
        - `features.md` - Feature list
        - `metrics.md` - Success metrics

        Generated by Braavo on {DateTime.UtcNow:yyyy-MM-dd}
        """;
}
